language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - cesargayo@gmail.com
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.projectKey=IWVG.SwC.CesarGayo -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=drachodran-github -Dsonar.login=$SONAR
